"""esquema inicial

Revision ID: e9d32eef416a
Revises: 
Create Date: 2026-08-10 04:57:25.297457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d32eef416a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cargo_actual', sa.String(), nullable=True),
    sa.Column('partido', sa.String(), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('aspiracion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('source_level', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('plataforma', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo IN ('oficial', 'medios', 'redes', 'no_verificado')", name='ck_fuentes_tipo'),
    sa.CheckConstraint('source_level BETWEEN 1 AND 4', name='ck_fuentes_source_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('kpi', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('variacion', sa.Float(), nullable=True),
    sa.Column('confianza', sa.String(), nullable=False),
    sa.Column('fecha_corte', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confianza IN ('alto', 'medio', 'bajo')", name='ck_metricas_confianza'),
    sa.ForeignKeyConstraint(['actor_id'], ['actores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('tema', sa.String(), nullable=True),
    sa.Column('sentimiento', sa.String(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('valor_numerico', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.Column('confianza', sa.String(), nullable=False),
    sa.Column('no_confirmado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confianza IN ('alto', 'medio', 'bajo')", name='ck_observaciones_confianza'),
    sa.CheckConstraint("sentimiento IN ('positivo', 'negativo', 'neutro')", name='ck_observaciones_sentimiento'),
    sa.ForeignKeyConstraint(['actor_id'], ['actores.id'], ),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observaciones')
    op.drop_table('metricas')
    op.drop_table('fuentes')
    op.drop_table('actores')
    # ### end Alembic commands ###
